# Setup
title:               BurntxNoodle
tagline:             'CompSci Student, Specialized in Security'
description:         '<p style="color:white">Welcome to the page!</p>Most of the content here are about topics in information security. See below for the list of different sections. <br> <br> <a href="https://burntxnoodle.github.io/" target="_blank">Click here</a> to go to the homepage.'
url:                 
baseurl:             '/'
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
